/**
 * Build-time snapshot generator for the data-driven sections.
 *
 * Fetches the live Google Sheet tabs (seating + photos) via the Sheets API,
 * parses them with the SAME parsers the runtime uses, and writes the offline
 * fallback snapshots the site ships with:
 *   - src/data/seating-snapshot.ts   (from the seating tab)
 *   - src/data/photos-snapshot.ts    (from the "Photos" tab)
 *
 * Run locally:  npm run sheets:pull   (reads .env.local / .env)
 * In CI:        run it before `npm run build`, with the key in a secret.
 *
 * Lenient by design: if the keys aren't set, or a tab is missing / errors, it
 * warns and KEEPS that section's existing snapshot (never fails the build) —
 * the snapshots are the safety net either way. Requires Node ≥ 22
 * (run via `node --experimental-strip-types`).
 */
import { writeFileSync } from "node:fs";
import { parseSeatingGrid } from "../src/lib/seating-parse.ts";
import { parsePhotoGrid } from "../src/lib/photos-parse.ts";

const ID = process.env.VITE_SHEETS_ID ?? process.env.SHEETS_ID;
const KEY = process.env.VITE_SHEETS_API_KEY ?? process.env.SHEETS_API_KEY;
const SEATING_RANGE = process.env.VITE_SHEETS_RANGE ?? "Sheet1";
const PHOTOS_RANGE = process.env.VITE_SHEETS_PHOTOS_RANGE ?? "Photos";

if (!ID || !KEY) {
  console.warn(
    "[sheets:pull] VITE_SHEETS_ID / VITE_SHEETS_API_KEY not set — skipping. " +
      "Keeping existing snapshots.",
  );
  process.exit(0);
}

async function fetchRows(range: string): Promise<string[][]> {
  const url =
    `https://sheets.googleapis.com/v4/spreadsheets/${ID}/values/` +
    `${encodeURIComponent(range)}?key=${KEY}&majorDimension=ROWS`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Sheets API ${res.status}: ${await res.text()}`);
  return ((await res.json()) as { values?: string[][] }).values ?? [];
}

function snapshotFile(exportName: string, typeName: string, value: unknown): string {
  return (
    `/* AUTO-GENERATED by scripts/pull-sheets.ts on ${new Date().toISOString()}.\n` +
    ` * Do not edit — run \`npm run sheets:pull\` to refresh from the live sheet.\n` +
    ` * Offline fallback used when the live fetch fails. */\n` +
    `import type { ${typeName} } from "../lib/${typeName === "SeatingData" ? "seating-parse" : "photos-parse"}";\n\n` +
    `export const ${exportName}: ${typeName} = ${JSON.stringify(value, null, 2)};\n`
  );
}

async function pull(
  label: string,
  range: string,
  parse: (rows: string[][]) => unknown,
  isEmpty: (v: any) => boolean,
  outPath: string,
  exportName: string,
  typeName: string,
): Promise<void> {
  try {
    const data = parse(await fetchRows(range));
    if (isEmpty(data)) {
      console.warn(`[sheets:pull] ${label}: parsed empty (range "${range}") — keeping snapshot.`);
      return;
    }
    writeFileSync(new URL(outPath, import.meta.url), snapshotFile(exportName, typeName, data));
    console.log(`[sheets:pull] ${label}: wrote ${outPath.split("/").pop()}.`);
  } catch (err) {
    console.warn(`[sheets:pull] ${label}: ${(err as Error).message} — keeping snapshot.`);
  }
}

await pull(
  "seating",
  SEATING_RANGE,
  parseSeatingGrid,
  (d) => d.guests.length === 0,
  "../src/data/seating-snapshot.ts",
  "seatingSnapshot",
  "SeatingData",
);
await pull(
  "photos",
  PHOTOS_RANGE,
  parsePhotoGrid,
  (d) => d.sections.length === 0,
  "../src/data/photos-snapshot.ts",
  "photosSnapshot",
  "PhotoData",
);
