/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceptionIndexRouteImport } from './routes/reception/index'
import { Route as CeremonyIndexRouteImport } from './routes/ceremony/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/reception/',
  path: '/reception/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeremonyIndexRoute = CeremonyIndexRouteImport.update({
  id: '/ceremony/',
  path: '/ceremony/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ceremony/': typeof CeremonyIndexRoute
  '/reception/': typeof ReceptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ceremony': typeof CeremonyIndexRoute
  '/reception': typeof ReceptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ceremony/': typeof CeremonyIndexRoute
  '/reception/': typeof ReceptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ceremony/' | '/reception/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ceremony' | '/reception'
  id: '__root__' | '/' | '/ceremony/' | '/reception/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CeremonyIndexRoute: typeof CeremonyIndexRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/reception'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremony/': {
      id: '/ceremony/'
      path: '/ceremony'
      fullPath: '/ceremony/'
      preLoaderRoute: typeof CeremonyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CeremonyIndexRoute: CeremonyIndexRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
